version: '2'
services:
  mysql:
        image: mysql:8.0
        container_name: mysql-server-80-paul
        command: --default-authentication-plugin=mysql_native_password
        working_dir: /application
        volumes:
          - .:/application
        restart: always
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=crud_db
          - MYSQL_USER=root
          - MYSQL_PASSWORD=root
        ports:
          - "8082:3306"
        volumes:
          - ./data/mysql:/var/lib/mysql
          - ./logs/mysql:/var/log/mysql
  website:
    container_name: miapp_7
    build:
      context: ./
    links:
      - "mysql:database"
    volumes:
      - ./src:/var/www/html
    ports:
      - 8090:80
    depends_on:
      - mysql
